name: Kotlin Quarkus native

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Set variables
      run: |
        echo "RELEASE_VERSION=1.0" >> $GITHUB_ENV
        echo "AWS_S3_CDN_BUCKET=qwe" >> $GITHUB_ENV
        echo "AWS_SECRET_KEY=qwe" >> $GITHUB_ENV
        echo "AWS_ACCESS_KEY=qwe" >> $GITHUB_ENV

    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 6.5

    - name: File system info
      run: |
        echo "===========> github.workspace var: ${{ github.workspace }}"
        echo "===========> pwd:"
        pwd
        echo "===========> ls -hal:"
        ls -hal
        echo "===========> ls -hal /src:"
        ls -hal ./src
        echo "===========> ls -hal /build:"
        ls -hal ./build

    - name: Run build with Gradle Wrapper
      run: |
        chmod +x ./gradlew
        ./gradlew build
